### ISSUE TITLE
`color-mod` function not working

### ISSUE THREAD

**Issue by vishalvijay** [FareFirst/styled-jsx-plugin-root-theme-provider#8]
In the current version (1.0.7), `color-mod` function is not working.

This issue can be because of 2 reason

**1st possibility**

`postcss-preset-env` is not yet ready for postcss 7.

There is an issue which `postcss-present-env` team working on (https://github.com/csstools/postcss-preset-env/issues/58)

**2nd possibility**
When tested with postcss version 6, it's not working there too. Maybe because of some configuration issue in this project.

**Comment by vishalvijay** [comment]
This issue will remain open until fix it properly

**Comment by jonathantneal** [comment]
The `color-mod` feature was dropped by the CSSWG, and so it is no longer in the process of becoming a standard. Thus, it is no longer supported using the `stage` option. You would have to manually add it using the `features` option.

See https://github.com/csstools/postcss-preset-env#features

**Comment by vishalvijay** [comment]
@jonathantneal Thanks for the info.

I'll do the same.

**Comment by vishalvijay** [comment]
Fixed with https://github.com/FareFirst/styled-jsx-plugin-root-theme-provider/pull/10
